// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: assets/proto_files/prices.proto

package proto_files

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DealerSizePrices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DealerPrice   int64                  `protobuf:"varint,1,opt,name=dealer_price,json=dealerPrice,proto3" json:"dealer_price,omitempty"`
	ClientPrice   int64                  `protobuf:"varint,2,opt,name=client_price,json=clientPrice,proto3" json:"client_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealerSizePrices) Reset() {
	*x = DealerSizePrices{}
	mi := &file_assets_proto_files_prices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealerSizePrices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealerSizePrices) ProtoMessage() {}

func (x *DealerSizePrices) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_files_prices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealerSizePrices.ProtoReflect.Descriptor instead.
func (*DealerSizePrices) Descriptor() ([]byte, []int) {
	return file_assets_proto_files_prices_proto_rawDescGZIP(), []int{0}
}

func (x *DealerSizePrices) GetDealerPrice() int64 {
	if x != nil {
		return x.DealerPrice
	}
	return 0
}

func (x *DealerSizePrices) GetClientPrice() int64 {
	if x != nil {
		return x.ClientPrice
	}
	return 0
}

type ClientSizePrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientPrice   int64                  `protobuf:"varint,1,opt,name=client_price,json=clientPrice,proto3" json:"client_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSizePrice) Reset() {
	*x = ClientSizePrice{}
	mi := &file_assets_proto_files_prices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSizePrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSizePrice) ProtoMessage() {}

func (x *ClientSizePrice) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_files_prices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSizePrice.ProtoReflect.Descriptor instead.
func (*ClientSizePrice) Descriptor() ([]byte, []int) {
	return file_assets_proto_files_prices_proto_rawDescGZIP(), []int{1}
}

func (x *ClientSizePrice) GetClientPrice() int64 {
	if x != nil {
		return x.ClientPrice
	}
	return 0
}

type SizePrice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Price:
	//
	//	*SizePrice_Dealer
	//	*SizePrice_Client
	Price         isSizePrice_Price `protobuf_oneof:"price"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SizePrice) Reset() {
	*x = SizePrice{}
	mi := &file_assets_proto_files_prices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizePrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizePrice) ProtoMessage() {}

func (x *SizePrice) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_files_prices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizePrice.ProtoReflect.Descriptor instead.
func (*SizePrice) Descriptor() ([]byte, []int) {
	return file_assets_proto_files_prices_proto_rawDescGZIP(), []int{2}
}

func (x *SizePrice) GetPrice() isSizePrice_Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *SizePrice) GetDealer() *DealerSizePrices {
	if x != nil {
		if x, ok := x.Price.(*SizePrice_Dealer); ok {
			return x.Dealer
		}
	}
	return nil
}

func (x *SizePrice) GetClient() *ClientSizePrice {
	if x != nil {
		if x, ok := x.Price.(*SizePrice_Client); ok {
			return x.Client
		}
	}
	return nil
}

type isSizePrice_Price interface {
	isSizePrice_Price()
}

type SizePrice_Dealer struct {
	Dealer *DealerSizePrices `protobuf:"bytes,1,opt,name=dealer,proto3,oneof"`
}

type SizePrice_Client struct {
	Client *ClientSizePrice `protobuf:"bytes,2,opt,name=client,proto3,oneof"`
}

func (*SizePrice_Dealer) isSizePrice_Price() {}

func (*SizePrice_Client) isSizePrice_Price() {}

var File_assets_proto_files_prices_proto protoreflect.FileDescriptor

const file_assets_proto_files_prices_proto_rawDesc = "" +
	"\n" +
	"\x1fassets/proto_files/prices.proto\x12\x05proto\"X\n" +
	"\x10DealerSizePrices\x12!\n" +
	"\fdealer_price\x18\x01 \x01(\x03R\vdealerPrice\x12!\n" +
	"\fclient_price\x18\x02 \x01(\x03R\vclientPrice\"4\n" +
	"\x0fClientSizePrice\x12!\n" +
	"\fclient_price\x18\x01 \x01(\x03R\vclientPrice\"y\n" +
	"\tSizePrice\x121\n" +
	"\x06dealer\x18\x01 \x01(\v2\x17.proto.DealerSizePricesH\x00R\x06dealer\x120\n" +
	"\x06client\x18\x02 \x01(\v2\x16.proto.ClientSizePriceH\x00R\x06clientB\a\n" +
	"\x05priceB\x19Z\x17project/pkg/proto_filesb\x06proto3"

var (
	file_assets_proto_files_prices_proto_rawDescOnce sync.Once
	file_assets_proto_files_prices_proto_rawDescData []byte
)

func file_assets_proto_files_prices_proto_rawDescGZIP() []byte {
	file_assets_proto_files_prices_proto_rawDescOnce.Do(func() {
		file_assets_proto_files_prices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assets_proto_files_prices_proto_rawDesc), len(file_assets_proto_files_prices_proto_rawDesc)))
	})
	return file_assets_proto_files_prices_proto_rawDescData
}

var file_assets_proto_files_prices_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_assets_proto_files_prices_proto_goTypes = []any{
	(*DealerSizePrices)(nil), // 0: proto.DealerSizePrices
	(*ClientSizePrice)(nil),  // 1: proto.ClientSizePrice
	(*SizePrice)(nil),        // 2: proto.SizePrice
}
var file_assets_proto_files_prices_proto_depIdxs = []int32{
	0, // 0: proto.SizePrice.dealer:type_name -> proto.DealerSizePrices
	1, // 1: proto.SizePrice.client:type_name -> proto.ClientSizePrice
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_assets_proto_files_prices_proto_init() }
func file_assets_proto_files_prices_proto_init() {
	if File_assets_proto_files_prices_proto != nil {
		return
	}
	file_assets_proto_files_prices_proto_msgTypes[2].OneofWrappers = []any{
		(*SizePrice_Dealer)(nil),
		(*SizePrice_Client)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assets_proto_files_prices_proto_rawDesc), len(file_assets_proto_files_prices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_assets_proto_files_prices_proto_goTypes,
		DependencyIndexes: file_assets_proto_files_prices_proto_depIdxs,
		MessageInfos:      file_assets_proto_files_prices_proto_msgTypes,
	}.Build()
	File_assets_proto_files_prices_proto = out.File
	file_assets_proto_files_prices_proto_goTypes = nil
	file_assets_proto_files_prices_proto_depIdxs = nil
}
