// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: assets/proto_files/order.proto

package proto_files

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GateType int32

const (
	GateType_GATE_TYPE_IND GateType = 0
	GateType_GATE_TYPE_RES GateType = 1
)

// Enum value maps for GateType.
var (
	GateType_name = map[int32]string{
		0: "GATE_TYPE_IND",
		1: "GATE_TYPE_RES",
	}
	GateType_value = map[string]int32{
		"GATE_TYPE_IND": 0,
		"GATE_TYPE_RES": 1,
	}
)

func (x GateType) Enum() *GateType {
	p := new(GateType)
	*p = x
	return p
}

func (x GateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GateType) Descriptor() protoreflect.EnumDescriptor {
	return file_assets_proto_files_order_proto_enumTypes[0].Descriptor()
}

func (GateType) Type() protoreflect.EnumType {
	return &file_assets_proto_files_order_proto_enumTypes[0]
}

func (x GateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GateType.Descriptor instead.
func (GateType) EnumDescriptor() ([]byte, []int) {
	return file_assets_proto_files_order_proto_rawDescGZIP(), []int{0}
}

type GateConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GateType      GateType               `protobuf:"varint,1,opt,name=gateType,proto3,enum=proto.GateType" json:"gateType,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	LiftTypeId    int64                  `protobuf:"varint,4,opt,name=liftTypeId,proto3" json:"liftTypeId,omitempty"`
	ColorOutId    int64                  `protobuf:"varint,5,opt,name=colorOutId,proto3" json:"colorOutId,omitempty"`
	DriveId       int32                  `protobuf:"varint,6,opt,name=driveId,proto3" json:"driveId,omitempty"`
	CycleAmountId int64                  `protobuf:"varint,7,opt,name=cycleAmountId,proto3" json:"cycleAmountId,omitempty"`
	Options       map[int32]int32        `protobuf:"bytes,8,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	GatePrice     int32                  `protobuf:"varint,9,opt,name=gatePrice,proto3" json:"gatePrice,omitempty"`
	Headroom      int32                  `protobuf:"varint,10,opt,name=headroom,proto3" json:"headroom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateConfig) Reset() {
	*x = GateConfig{}
	mi := &file_assets_proto_files_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateConfig) ProtoMessage() {}

func (x *GateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_files_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateConfig.ProtoReflect.Descriptor instead.
func (*GateConfig) Descriptor() ([]byte, []int) {
	return file_assets_proto_files_order_proto_rawDescGZIP(), []int{0}
}

func (x *GateConfig) GetGateType() GateType {
	if x != nil {
		return x.GateType
	}
	return GateType_GATE_TYPE_IND
}

func (x *GateConfig) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *GateConfig) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GateConfig) GetLiftTypeId() int64 {
	if x != nil {
		return x.LiftTypeId
	}
	return 0
}

func (x *GateConfig) GetColorOutId() int64 {
	if x != nil {
		return x.ColorOutId
	}
	return 0
}

func (x *GateConfig) GetDriveId() int32 {
	if x != nil {
		return x.DriveId
	}
	return 0
}

func (x *GateConfig) GetCycleAmountId() int64 {
	if x != nil {
		return x.CycleAmountId
	}
	return 0
}

func (x *GateConfig) GetOptions() map[int32]int32 {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *GateConfig) GetGatePrice() int32 {
	if x != nil {
		return x.GatePrice
	}
	return 0
}

func (x *GateConfig) GetHeadroom() int32 {
	if x != nil {
		return x.Headroom
	}
	return 0
}

type OrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderGates    []*GateConfig          `protobuf:"bytes,1,rep,name=orderGates,proto3" json:"orderGates,omitempty"`
	Products      map[int32]int32        `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	mi := &file_assets_proto_files_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assets_proto_files_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_assets_proto_files_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderRequest) GetOrderGates() []*GateConfig {
	if x != nil {
		return x.OrderGates
	}
	return nil
}

func (x *OrderRequest) GetProducts() map[int32]int32 {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_assets_proto_files_order_proto protoreflect.FileDescriptor

const file_assets_proto_files_order_proto_rawDesc = "" +
	"\n" +
	"\x1eassets/proto_files/order.proto\x12\x05proto\"\x97\x03\n" +
	"\n" +
	"GateConfig\x12+\n" +
	"\bgateType\x18\x01 \x01(\x0e2\x0f.proto.GateTypeR\bgateType\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1e\n" +
	"\n" +
	"liftTypeId\x18\x04 \x01(\x03R\n" +
	"liftTypeId\x12\x1e\n" +
	"\n" +
	"colorOutId\x18\x05 \x01(\x03R\n" +
	"colorOutId\x12\x18\n" +
	"\adriveId\x18\x06 \x01(\x05R\adriveId\x12$\n" +
	"\rcycleAmountId\x18\a \x01(\x03R\rcycleAmountId\x128\n" +
	"\aoptions\x18\b \x03(\v2\x1e.proto.GateConfig.OptionsEntryR\aoptions\x12\x1c\n" +
	"\tgatePrice\x18\t \x01(\x05R\tgatePrice\x12\x1a\n" +
	"\bheadroom\x18\n" +
	" \x01(\x05R\bheadroom\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xbd\x01\n" +
	"\fOrderRequest\x121\n" +
	"\n" +
	"orderGates\x18\x01 \x03(\v2\x11.proto.GateConfigR\n" +
	"orderGates\x12=\n" +
	"\bproducts\x18\x02 \x03(\v2!.proto.OrderRequest.ProductsEntryR\bproducts\x1a;\n" +
	"\rProductsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01*0\n" +
	"\bGateType\x12\x11\n" +
	"\rGATE_TYPE_IND\x10\x00\x12\x11\n" +
	"\rGATE_TYPE_RES\x10\x01B\x19Z\x17project/pkg/proto_filesb\x06proto3"

var (
	file_assets_proto_files_order_proto_rawDescOnce sync.Once
	file_assets_proto_files_order_proto_rawDescData []byte
)

func file_assets_proto_files_order_proto_rawDescGZIP() []byte {
	file_assets_proto_files_order_proto_rawDescOnce.Do(func() {
		file_assets_proto_files_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assets_proto_files_order_proto_rawDesc), len(file_assets_proto_files_order_proto_rawDesc)))
	})
	return file_assets_proto_files_order_proto_rawDescData
}

var file_assets_proto_files_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_assets_proto_files_order_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_assets_proto_files_order_proto_goTypes = []any{
	(GateType)(0),        // 0: proto.GateType
	(*GateConfig)(nil),   // 1: proto.GateConfig
	(*OrderRequest)(nil), // 2: proto.OrderRequest
	nil,                  // 3: proto.GateConfig.OptionsEntry
	nil,                  // 4: proto.OrderRequest.ProductsEntry
}
var file_assets_proto_files_order_proto_depIdxs = []int32{
	0, // 0: proto.GateConfig.gateType:type_name -> proto.GateType
	3, // 1: proto.GateConfig.options:type_name -> proto.GateConfig.OptionsEntry
	1, // 2: proto.OrderRequest.orderGates:type_name -> proto.GateConfig
	4, // 3: proto.OrderRequest.products:type_name -> proto.OrderRequest.ProductsEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_assets_proto_files_order_proto_init() }
func file_assets_proto_files_order_proto_init() {
	if File_assets_proto_files_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assets_proto_files_order_proto_rawDesc), len(file_assets_proto_files_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_assets_proto_files_order_proto_goTypes,
		DependencyIndexes: file_assets_proto_files_order_proto_depIdxs,
		EnumInfos:         file_assets_proto_files_order_proto_enumTypes,
		MessageInfos:      file_assets_proto_files_order_proto_msgTypes,
	}.Build()
	File_assets_proto_files_order_proto = out.File
	file_assets_proto_files_order_proto_goTypes = nil
	file_assets_proto_files_order_proto_depIdxs = nil
}
