syntax = "proto3";

package proto;
option go_package = "project/pkg/proto_files";

message GateConfig {
  GateType gateType = 1;
  int32 width = 2;
  int32 height = 3;
  int64 liftTypeId = 4;
  int64 colorOutId = 5;
  int32 driveId = 6;
  int64 cycleAmountId = 7;
  map<int32, int32> options = 8;
  int32 gatePrice = 9;
  int32 headroom = 10;
}

enum GateType {
  GATE_TYPE_IND = 0;
  GATE_TYPE_RES = 1;
}

message OrderRequest {
  repeated GateConfig orderGates = 1;
  map<int32, int32> products = 2;
}
